poppy_main_controls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.poppyMainController.index, name='index'),
    ]

poppy_web_app/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
url(r'^', include('poppy_main_controls.urls', namespace='poppy_main_controls')),
]

poppy_main_controls/views.py
from django.shortcuts import render
from poppy_humanoid import PoppyHumanoid

import time, os

#~ hasPoppy = False

#~ if hasPoppy:
    #~ try:
        #~ poppy = PoppyHumanoid()
        #~ time.sleep(0.1)
    #~ except Exception,e:
            #~ print "could not create poppy object"
            #~ print e
    
#~ def index(request):
    #~ context = {}
    #~ context['other'] = request.POST
    
    


    #~ if 'compliant' in request.POST.keys():
        #~ if hasPoppy:
            #~ #poppy.compliant =True
            #~ context['other'] = poppy.r_ankle_y.present_position
            #~ time.sleep(0.1)

    #~ if 'notCompliant' in request.POST.keys():
        #~ if hasPoppy:
            #~ poppy.compliant = False
            #~ time.sleep(0.1)

    #~ if  'speak' in request.POST.keys():
        #~ os.system('picospeaker -l "fr-FR" "Bonjour je suis poppy"')

    #~ return render(request, 'poppy_main_controls/index.html',context )
    
class PoppyMainController:
    def __init__(self, hasPoppy=True):
        self.hasPoppy = hasPoppy
        self.snapStarted = False
        self.notebookStarted = False
        
        self.context = {}
        self.context['notebookButton'] = "Start"
        self.context['notebookText'] = ""
        
    def index(self, request):
        self.context['other'] = request.POST
        if  'speak' in request.POST.keys() :
            if len(request.POST["toSay"]) == 0:
                self.context["speakerror"] = "Enter some text first!"
            else:
                self.context["speakerror"] = request.POST["toSay"]
                try:
                    os.system('picospeaker -l "fr-FR" "'+request.POST["toSay"]+'"')
                except:
                    print "error: could not use TTS"
                    
        #~ if 'notebook' in request.POST.keys() :
            #~ try:
                #~ os.system('ipython notebook --ip 0.0.0.0 --no-mathjax --no-browser')
            #~ except:
                #~ print "error: could not start ipython server"       
            #~ self.context['notebookButton'] = "Stop"
            #~ self.context['notebookText'] = 'Now open <a href="http://poppy.local:8888/notebooks/dev/poppy-humanoid/software/notebooks/TTFX.ipynb">http://poppy.local:8888/notebooks/dev/poppy-humanoid/software/notebooks/TTFX.ipynb <\a>'
        return render(request, 'poppy_main_controls/index.html',self.context )
        
        
poppyMainController = PoppyMainController()
        
        

poppy_main_controls/templates/poppy_main_controls/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'poppy-web-style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'poppy_main_controls/poppy_main_controls_style.css' %}" />


<!--
<link rel="stylesheet" type="text/css" href="{% static 'basic_controls/poppy-web-style.css' %}" />
<link rel="stylesheet" type="text/css" href="poppy-web-style.css" />-->
<div id="poppymaindiv">

<h1 id="title">Poppy Humanoid main controls</h1>

<div class="row">

<!--<div class="smallcontainer3 height40">
<h2>Quick controls</h2>
<div class="smallcontainer2">
<form action="{% url 'poppy_main_controls:index' %}" method="post">
{% csrf_token %}
<input type="submit" value="compliant" name="compliant" class="button"/>
</form>
</div>
<div class="smallcontainer2">
<form action="{% url 'poppy_main_controls:index' %}" method="post">
{% csrf_token %}
<input type="submit" value="not compliant" name="not compliant" class="button"/>
</form>
</div>
<div style="clear: both;"></div>
<div class="smallcontainer2">
<form action="{% url 'poppy_main_controls:index' %}" method="post">
{% csrf_token %}
<input type="submit" value="stand" name="stand" class="button"/>
</form>
</div>
<div class="smallcontainer2">
<form action="{% url 'poppy_main_controls:index' %}" method="post">
{% csrf_token %}
<input type="submit" value="sit" name="sit" class="button"/>
</form>
</div>
</div>-->

<div class="smallcontainer3 height40">
<h2>Text to Speach</h2>
<form action="{% url 'poppy_main_controls:index' %}" method="post">
{% csrf_token %}
Enter some text here:
<input type="text" value="" name="toSay" />
<input type="submit" value="speak" name="speak" class="button"/>
</form>
<p>{{speakerror}}</p>
</div>

<!--<div class="smallcontainer3 height40">
<h2>Start servers</h2>
<div class="smallcontainer2">
<form action="{% url 'poppy_main_controls:index' %}" method="post">
{% csrf_token %}
Ipython notebook server
<input type="submit" value="{{notebookButton}}" name="notebook" class="button"/>
</form>
{{notebookText}}
</div>
<div class="smallcontainer2">
Ipython notebook allows to see code, launch demos and even code yourself on the robot!
</div>
<div style="clear: both;"></div>
<div class="smallcontainer2">
<form action="{% url 'poppy_main_controls:index' %}" method="post">
{% csrf_token %}
<input type="submit" value="stand" name="stand" class="button"/>
</form>
</div>
<div class="smallcontainer2">
<form action="{% url 'poppy_main_controls:index' %}" method="post">
{% csrf_token %}
<input type="submit" value="sit" name="sit" class="button"/>
</form>
</div>
</div>-->

</div> <!-- of row -->

</div> <!-- of main div -->

<p>{{other}}</p>